# Generated by Django 6.0.4 on 2026-05-19 18:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolarPanel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], default='offline', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solar_panels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solar Panel',
                'verbose_name_plural': 'Solar Panels',
            },
        ),
        migrations.CreateModel(
            name='PanelPosition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('theoretical_azimuth', models.DecimalField(decimal_places=2, max_digits=8)),
                ('actual_azimuth', models.DecimalField(decimal_places=2, max_digits=8)),
                ('theoretical_elevation', models.DecimalField(decimal_places=2, max_digits=8)),
                ('actual_elevation', models.DecimalField(decimal_places=2, max_digits=8)),
                ('mode', models.CharField(choices=[('automatic', 'Automatic'), ('manual', 'Manual')], default='automatic', max_length=20)),
                ('panel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='solar_tracker_system.solarpanel')),
            ],
            options={
                'verbose_name': 'Panel Position',
                'verbose_name_plural': 'Panel Positions',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('panel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='solar_tracker_system.solarpanel')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DashboardData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('voltage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current', models.DecimalField(decimal_places=2, max_digits=10)),
                ('luminosity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('power', models.DecimalField(decimal_places=2, max_digits=10)),
                ('energetic_efficiency', models.DecimalField(decimal_places=2, max_digits=5)),
                ('energy', models.DecimalField(decimal_places=2, max_digits=10)),
                ('panel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_data', to='solar_tracker_system.solarpanel')),
            ],
            options={
                'verbose_name': 'Dashboard Data',
                'verbose_name_plural': 'Dashboard Data',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['panel', 'timestamp'], name='solar_track_panel_i_c0ef54_idx')],
            },
        ),
    ]
