# Generated by Django 6.0.4 on 2026-05-13 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Painel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], default='offline', max_length=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('utilizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paineis', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Painel',
                'verbose_name_plural': 'Painéis',
            },
        ),
        migrations.CreateModel(
            name='Localizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('painel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localizacoes', to='solar_tracker_system.painel')),
            ],
            options={
                'verbose_name': 'Localização',
                'verbose_name_plural': 'Localizações',
                'ordering': ['-data_hora'],
            },
        ),
        migrations.CreateModel(
            name='PosicaoPainel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('azimute_teorico', models.DecimalField(decimal_places=2, max_digits=8)),
                ('azimute_real', models.DecimalField(decimal_places=2, max_digits=8)),
                ('elevacao_teorico', models.DecimalField(decimal_places=2, max_digits=8)),
                ('elevacao_real', models.DecimalField(decimal_places=2, max_digits=8)),
                ('modo', models.CharField(choices=[('automatico', 'Automático'), ('manual', 'Manual')], default='automatico', max_length=20)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('painel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posicoes', to='solar_tracker_system.painel')),
            ],
            options={
                'verbose_name': 'Posição do Painel',
                'verbose_name_plural': 'Posições do Painel',
                'ordering': ['-data_hora'],
            },
        ),
        migrations.CreateModel(
            name='DadosDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tensao', models.DecimalField(decimal_places=2, max_digits=10)),
                ('corrente', models.DecimalField(decimal_places=2, max_digits=10)),
                ('luminosidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('potencia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('eficiencia', models.DecimalField(decimal_places=2, max_digits=5)),
                ('energia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_hora', models.DateTimeField(auto_now=True)),
                ('painel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dados_dashboard', to='solar_tracker_system.painel')),
            ],
            options={
                'verbose_name': 'Dado Dashboard',
                'verbose_name_plural': 'Dados Dashboard',
                'ordering': ['-data_hora'],
                'indexes': [models.Index(fields=['data_hora'], name='solar_track_data_ho_26e216_idx')],
            },
        ),
    ]
