# Generated by Django 6.0.4 on 2026-05-29 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_tracker_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dashboarddata',
            options={'get_latest_by': 'timestamp', 'ordering': ['-timestamp'], 'verbose_name': 'Dashboard Data', 'verbose_name_plural': 'Dashboard Data'},
        ),
        migrations.AlterModelOptions(
            name='panelposition',
            options={'get_latest_by': 'timestamp', 'ordering': ['-timestamp'], 'verbose_name': 'Panel Position', 'verbose_name_plural': 'Panel Positions'},
        ),
        migrations.RemoveField(
            model_name='solarpanel',
            name='status',
        ),
        migrations.AddField(
            model_name='solarpanel',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
