# Generated by Django 6.0.4 on 2026-05-20 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_tracker_system', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboarddata',
            name='energetic_efficiency',
        ),
        migrations.AddField(
            model_name='panelposition',
            name='tracking_efficiency',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
