# Generated by Django 6.0.4 on 2026-05-20 12:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_tracker_system', '0002_remove_dashboarddata_energetic_efficiency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboarddata',
            name='energy',
        ),
        migrations.CreateModel(
            name='DailyData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField()),
                ('total_energy', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tracking_efficiency_avg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('panel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_data', to='solar_tracker_system.solarpanel')),
            ],
            options={
                'verbose_name': 'Daily Data',
                'verbose_name_plural': 'Daily Data',
                'ordering': ['-date'],
                'unique_together': {('panel', 'date')},
            },
        ),
    ]
