# Generated by Django 6.0.4 on 2026-05-30 19:46

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_tracker_system', '0002_alter_dashboarddata_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panelposition',
            name='mode',
        ),
        migrations.CreateModel(
            name='RemoteControl',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('manual_azimuth', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8)),
                ('manual_elevation', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8)),
                ('mode', models.CharField(choices=[('automatic', 'Automatic'), ('manual', 'Manual')], default='automatic', max_length=20)),
                ('panel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remote_controls', to='solar_tracker_system.solarpanel')),
            ],
            options={
                'verbose_name': 'Remote Control',
                'verbose_name_plural': 'Remote Controls',
                'ordering': ['-timestamp'],
                'get_latest_by': 'timestamp',
            },
        ),
    ]
