# Generated by Django 6.0.4 on 2026-05-30 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_tracker_system', '0003_remove_panelposition_mode_remotecontrol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remotecontrol',
            name='manual_azimuth',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='remotecontrol',
            name='manual_elevation',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
